<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AssemblyName>UvcInspector</AssemblyName>
    <Version>2.0.1</Version>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../../assets/App.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../UvcInspector.Core/UvcInspector.Core.csproj" /><Resource Include="../../assets/App.ico" Link="App.ico" /></ItemGroup>
</Project>
